In [148]:
import numpy as np
import matplotlib.pyplot as plt
import time

## Topic 1: Declaring an array, dtype, matrix

In [138]:
L=[1,2,3]
a=np.array(L)

L=[[1,2],[2,3],[4,5]]
a=np.array(L)

L=[['1','2'],['2','3']]
a=np.array(L)

a=np.ones((3,3))
a=np.zeros((3,3))
#print(a)

a=np.arange(4,10,0.1)
a=np.flip(np.arange(99,39,-1)*0.1)

a=np.linspace(4,10,21)

a=np.eye(5)

#np.random.seed(10)
a=np.random.randn(10)
a=np.random.rand(10)

a=np.random.randint(5,10,12)
print(a)

print(a.reshape((3,4)))
#_=plt.hist(a,100)

[7 8 8 7 6 7 7 8 7 6 6 5]
[[7 8 8 7]
 [6 7 7 8]
 [7 6 6 5]]


## Topic 1': Operating on array elements

In [13]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a=np.array([[4,1],[2,3]])
b=np.array([[4,1],[2,3]])

a**b

array([[256,   1],
       [  4,  27]])

## Topic 2: Slicing a numpy array

In [169]:
a=np.arange(10)*2
#a[5:8]=a[6:9]**2
tmp=a[:5].copy()
a[:5]=a[5:]
a[5:]=tmp

a=np.arange(10)*2

np.concatenate([a[3:],a[:3]])

array([ 6,  8, 10, 12, 14, 16, 18,  0,  2,  4])

## Topic 3: Array properties: length, sum, mean, std, etc

In [67]:
a=np.arange(11)
b=np.concatenate([np.zeros(5), [5],np.ones(5)*10])
c=np.ones(11)*5
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  0.  0.  0.  0.  5. 10. 10. 10. 10. 10.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [68]:
print(np.mean(a),np.mean(b),np.mean(c))
print(np.std(a),np.std(b),np.std(c))
#np.std(a)**2, np.var(a)

5.0 5.0 5.0
3.1622776601683795 4.767312946227961 0.0


In [127]:
a=np.arange(125).reshape([5,5,5])
print(a)


[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]


## Topic 4: Properties of array slices

In [131]:
print(a[3,:3,:3])

[[75 76 77]
 [80 81 82]
 [85 86 87]]


## Topic 6: Basic linear algebra: Matrix-vector product

In [158]:
N=1000
M=N

A=np.arange(M*N).reshape([M,N])
b=np.arange(N)

# Goal: c=Ab
st=time.time()
A.dot(b)
#print()
nptime=time.time()-st

st=time.time()
c=np.zeros(M)
for i in range(M):
    for j in range(N):
        c[i]+=A[i,j]*b[j]
print((time.time()-st)/nptime)

626.487434875881


In [145]:
print(A)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
